import 'package:riverpod/riverpod.dart';
import 'package:score_card/models/hole.dart';

final holeProvider = StateNotifierProvider<HoleNotifier, List<Hole>>((ref) => HoleNotifier());

class HoleNotifier extends StateNotifier<List<Hole>> {
  HoleNotifier()
    : super([
        Hole(
          number: 1,
          par: 4,
          handicap: 5,
          distanceWhite: 381,
          distanceYellow: 363,
          distanceBlue: 331,
          distanceRed: 300,
        ),
        Hole(
          number: 2,
          par: 5,
          handicap: 3,
          distanceWhite: 517,
          distanceYellow: 472,
          distanceBlue: 472,
          distanceRed: 300,
        ),
        Hole(
          number: 3,
          par: 4,
          handicap: 11,
          distanceWhite: 345,
          distanceYellow: 314,
          distanceBlue: 287,
          distanceRed: 255,
        ),
        Hole(
          number: 4,
          par: 3,
          handicap: 15,
          distanceWhite: 166,
          distanceYellow: 135,
          distanceBlue: 114,
          distanceRed: 110,
        ),
        Hole(
          number: 5,
          par: 5,
          handicap: 17,
          distanceWhite: 443,
          distanceYellow: 390,
          distanceBlue: 347,
          distanceRed: 347,
        ),
        Hole(
          number: 6,
          par: 5,
          handicap: 1,
          distanceWhite: 443,
          distanceYellow: 387,
          distanceBlue: 343,
          distanceRed: 297,
        ),
        Hole(
          number: 7,
          par: 3,
          handicap: 13,
          distanceWhite: 166,
          distanceYellow: 170,
          distanceBlue: 144,
          distanceRed: 144,
        ),
        Hole(
          number: 8,
          par: 4,
          handicap: 7,
          distanceWhite: 313,
          distanceYellow: 284,
          distanceBlue: 244,
          distanceRed: 234,
        ),
        Hole(
          number: 9,
          par: 3,
          handicap: 9,
          distanceWhite: 166,
          distanceYellow: 143,
          distanceBlue: 129,
          distanceRed: 101,
        ),
        Hole(
          number: 10,
          par: 4,
          handicap: 16,
          distanceWhite: 275,
          distanceYellow: 264,
          distanceBlue: 252,
          distanceRed: 241,
        ),
        Hole(
          number: 11,
          par: 5,
          handicap: 6,
          distanceWhite: 424,
          distanceYellow: 169,
          distanceBlue: 379,
          distanceRed: 366,
        ),
        Hole(
          number: 12,
          par: 3,
          handicap: 4,
          distanceWhite: 169,
          distanceYellow: 158,
          distanceBlue: 138,
          distanceRed: 121,
        ),
        Hole(
          number: 13,
          par: 5,
          handicap: 12,
          distanceWhite: 419,
          distanceYellow: 398,
          distanceBlue: 370,
          distanceRed: 352,
        ),
        Hole(
          number: 14,
          par: 4,
          handicap: 2,
          distanceWhite: 368,
          distanceYellow: 358,
          distanceBlue: 307,
          distanceRed: 256,
        ),
        Hole(
          number: 15,
          par: 3,
          handicap: 8,
          distanceWhite: 166,
          distanceYellow: 138,
          distanceBlue: 123,
          distanceRed: 111,
        ),
        Hole(
          number: 16,
          par: 4,
          handicap: 14,
          distanceWhite: 332,
          distanceYellow: 260,
          distanceBlue: 227,
          distanceRed: 216,
        ),
        Hole(
          number: 17,
          par: 3,
          handicap: 10,
          distanceWhite: 176,
          distanceYellow: 160,
          distanceBlue: 146,
          distanceRed: 138,
        ),
        Hole(
          number: 18,
          par: 5,
          handicap: 18,
          distanceWhite: 433,
          distanceYellow: 411,
          distanceBlue: 390,
          distanceRed: 339,
        ),
      ]);
}
